author:
  name: OUFC
baseURL: https://example.com
languageCode: en
menu:
  main:
    - name: About
      url: /about
params:
  description: Example site for the Hugo's Blogpaper theme
title: OUFC
theme: Blogpaper
publishDir: docs
